### ISSUE TITLE
Name clash distro-wide

### ISSUE THREAD

**Issue by vaygr** [tamentis/mdp#10]
Unfortunately a rather popular software project of [the same name](https://github.com/visit1985/mdp) made it to many distributions.

In [Source Mage](https://sourcemage.org) it wasn't the case, but it is in many others like Arch or Debian. I saw under #8 that it was packaged as `tamentis-mdp` (the link needs to be corrected on the main page, but I'm not even sure if the package is still there).

When I recently packaged mdp for Arch in AUR I decided to do it under `mdp-pass`, so this issue is to not ask for project rename, but to get some feedback on packaging guidelines in case a package of the same name exists. Maybe `mdpass`?

**Comment by tamentis** [comment]
I think `mdp-password-manager` is probably the most explicit name for a package. Would that also impact the binary under AUR?

**Comment by vaygr** [comment]
Yes, you can take a look at the modifications I did in https://aur.archlinux.org/packages/mdp-pass (mostly [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mdp-pass) and [mdp-name.patch](https://aur.archlinux.org/cgit/aur.git/tree/mdp-name.patch?h=mdp-pass)).

I had to rename all references in the man page so users are not confused and are looking at the right reference for commands.

Given binary conflict, yes, it should be different as well, but `mdp-password-manager` seems like too long (hence I proposed `mdpass` or `mdp-pass`).

Another option is to just add package `conflicts` line, so both mdp-s are never installed together, but it seems wrong.

Once we come to the conclusion on the best way forward, I can submit it under a more favorable name and request removal for the old one.

**Comment by tamentis** [comment]
Okay then, if the binary has to be renamed too `mdp-pass` works. Thank you so much for dealing with this.
