### ISSUE TITLE
moving characters won't make the file writen

### ISSUE THREAD

**Issue by fluxspir** [tamentis/mdp#5]
If I move some characters in a line, mdp won't write the file, keeping the old one.
exemple : 
from
 credit card                1234 1234 1234 1234            02/2020            025
to
 credit card                1234123412341234               02/2020            025

this happen when i remove "spaced" and move them along to keep alignment.
Further testes needed to see if this happens too with \w \d and others characters

**Comment by tamentis** [comment]
Fixed in 0.7.4
