### ISSUE TITLE
[website] package is available for Fedora

### ISSUE THREAD

**Issue by nixpanic** [tamentis/mdp#8]
Hi,

I was looking for the source of [the website](https://tamentis.com/projects/mdp/), but am unable to find them. So, no pull request, but just an issue that should be easy to fix.

In current versions of Fedora, `mdp` (the command) can be installed through the `tamentis-mdp` package. This has been packaged by Raphael Groner. It would be nice to add that to the website.

Thanks,
Niels

**Comment by tamentis** [comment]
Thanks for letting me know! I have added a link to https://apps.fedoraproject.org/packages/mdp on the website, I'm not sure if the package name is `mdp` or `tamentis-mdp` however.

**Comment by nixpanic** [comment]
Thanks! The updated page looks good to me. The source package name is `mdp`, but to install it `dnf install tamentis-mdp` is needed.
